version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  unleash:
    image: unleashorg/unleash-server:4.6.0
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      DATABASE_SSL: "false"
    depends_on:
      - postgres
    ports:
      - "4242:4242"
  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      UNLEASH_URL: http://unleash:4242/api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - unleash
