apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-ejemplo-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-ejemplo
      version: green
  template:
    metadata:
      labels:
        app: ms-ejemplo
        version: green
    spec:
      containers:
      - name: ms-ejemplo
        image: ms-ejemplo:latest  # Se reemplaza en el pipeline
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:password@postgres:5432/postgres"
